"! @testing /DMO/CL_I_TRAVEL_TUM
"! @testing /DMO/CL_C_TRAVEL_TUM
"! @testing /DMO/CL_FLIGHT_LEGACY
"! @testing FUGR:/DMO/FLIGHT_TRAVEL_API
CLASS ltc DEFINITION FINAL INHERITING FROM /dmo/tc_flight_travel_api FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
